### ISSUE TITLE
Infra as code prerequisite: document example data-source-config.json

### ISSUE THREAD

**Issue by valentinsavenko** [grafana/github-datasource#169]
I was easily able to setup the datasource _manually_ but we are deploying into multiple environments automatically using the [prom-operator](https://github.com/prometheus-operator/prometheus-operator) e.g. the Elasticsearch plugin [docu is giving a clear structure to follow](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#configure-the-data-source-with-provisioning)

Even trying to guess [based on the type definition ](https://github.com/grafana/github-datasource/blob/main/src/types.ts) does not help me to make it work from yaml/ json e.g.
```promop:
    grafana:
        additionalDataSources:
            - name: GitHub Repo Insights
              type: GitHub
              jsonData:
                  accessToken: bla
```
Could you point me the correct _internal_ names of the settings? Or provide an example file/ documentation?

**Comment by valentinsavenko** [comment]
Based on [this other external plugin](https://github.com/grafana/x-ray-datasource#using-a-credentials-file) I was able to guess the correct settings, but I think it still makes sense to document this properly. 

working: 
```
promop:
    grafana:
        additionalDataSources:
            - name: GitHub Repo Insights
              type: grafana-github-datasource
              jsonData:
                  owner: ""
                  repository: ""
              secureJsonData:
                  accessToken: "nope"
```
