### ISSUE TITLE
GitHub App Permissions and provisioning

### ISSUE THREAD

**Issue by chewrocca** [grafana/github-datasource#370]
What permissions are needed now that this datasource is available with GitHub App authentication? 

https://github.com/grafana/github-datasource/issues/365

And is this the proper way to provision this datasource?

```yaml
- name: GitHub Repo Insights
  type: 'grafana-github-datasource'
  disabled: false
  jsonData:
    owner: ''
    repository: ''
    selectedAuthType: 'github-app'
    appId: "123456"
    installationId: "12345678"
  secureJsonData:
    privateKey: $__file{/local/client_secret.pem}
```
