### ISSUE TITLE
Docs do not cover how to provision enterprise datasource

### ISSUE THREAD

**Issue by cloudymax** [grafana/github-datasource#456]
The documentation does not provide guidance on the correct fields to use when provisioning the datasource for an enterprise installation.

I am unable to find how to change the connection type to 'Enterprise' and how to supply the custom URL use an additional datasource.

<img width="924" alt="Image" src="https://github.com/user-attachments/assets/9d7ea3f3-047a-4fd2-b622-02662565e763" />

from https://grafana.com/docs/plugins/grafana-github-datasource/latest/setup/provisioning/

```yaml
apiVersion: 1

datasources:
  - name: GitHub (Personal Access Token)
    type: grafana-github-datasource
    jsonData:
      selectedAuthType: personal-access-token
    secureJsonData:
      accessToken: <your_access_token>

  - name: GitHub (App)
    type: grafana-github-datasource
    jsonData:
      selectedAuthType: github-app
      appId: <your_app_id>
      installationId: <your_installation_id>
    secureJsonData:
      privateKey: <your_private_key>
```

**Comment by cloudymax** [comment]
Found what i was looking for in: https://github.com/grafana/github-datasource/blob/main/src/types/config.ts

working definition:

```yaml
              - name: GitHub
                type: grafana-github-datasource
                jsonData:
                  selectedAuthType: github-app
                  appId: "123"
                  installationId: "456"
                  githubPlan: github-enterprise-server
                  githubUrl: https://github.my.company.com
                secureJsonData:
                  privateKey: $__file{/etc/secrets/private-key/private-key.pem}
```
